spring.application.name=blendy
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=blendy;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=blendy
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jackson.deserialization.fail-on-null-for-primitives=false

